theme: jekyll-theme-cayman
title: Welcome to the homepage! 
description: Hello, I am Eli MacDonald I went to Abington Senior High School in Abington Pennsylvania. In my free time I enjoy playing video games, riding my skateboard, and spending time with my friends. 
